all: compile

compile:
	
	gcc FunctionsTrab3.c -c -O0 -g3 -Wall -fmessage-length=0 -std=c99
	gcc FunctionsTrab3.o trab3.c -Wall -g -lm -o trab3	
	
run:
		
	./trab3
	
clean:
	rm trab3 FunctionsTrab3.o
		
